### ISSUE TITLE
 problem with Recommendations on GCP with TensorFlow and WALS

### ISSUE THREAD

**Issue by VictorChavez07** [GoogleCloudPlatform/tensorflow-recommendation-wals#12]
WARNING: The `gcloud ml-engine` commands have been renamed and will soon be removed. Please use `gcloud ai-platform` instead.
Traceback (most recent call last):
  File "/home/contacto/miniconda2/envs/tfrec/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/contacto/miniconda2/envs/tfrec/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/contacto/tensorflow-recommendation-wals/wals_ml_engine/trainer/task.py", line 22, in <module>
    import model
  File "trainer/model.py", line 25, in <module>
    import wals
  File "trainer/wals.py", line 21, in <module>
    from tensorflow.contrib.factorization.python.ops import factorization_ops
ImportError: No module named contrib.factorization.python.ops
Tue Nov 26 01:21:40 UTC 2019

**Comment by lukmanr** [comment]
Fixed install to specify TensorFlow 1.x.
